version: '3.6'

services:
  db:
    image: postgres:14.0-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: test_db
    volumes:
      - data:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  data:
